### ISSUE TITLE
Links are removed from the content

### ISSUE THREAD

**Issue by EpocDotFr** [EpocDotFr/webtodotxt#21]

**Comment by Strubbl** [comment]
This bug may be cause by the current tag regex, which i tried to fix in https://github.com/EpocDotFr/todotxtio/pull/11

The current tag regex would match a line with an url like ` https://example.com`, because it would see the string `  https:` as a tag.

**Comment by EpocDotFr** [comment]
I released a new version of todotxtio containing your fix.
