### ISSUE TITLE
Provide release or demo version

### ISSUE THREAD

**Issue by senpl** [EpocDotFr/webtodotxt#31]
Currently there is no quick way to check app. It should be possible without installing all python dependencies.

**Comment by EpocDotFr** [comment]
As it's a web app, I can't provide a release version without requiring you to install the required Python dependencies. I may set up a demo version hosted somewhere but honestly I don't want to deal with the maintenance or take time to setting it up (I personally no more use Web Todo.txt).

It's a small project, so you just have to set up a virtualenv (so your global Python packages will not be bloated with Web Todo.txt ones) and run `pip install -r requirements.txt` (as you can see, the [installation instructions](https://github.com/EpocDotFr/webtodotxt#installation) are short).

**Comment by Strubbl** [comment]
@EpocDotFr what are you using instead of web todo.txt?

**Comment by EpocDotFr** [comment]
@Strubbl I no more use Todo.txt files nor self-hosted app. I'm using Remember The Milk instead.
